# Generated by Django 3.0.7 on 2020-06-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200629_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
    ]
