# Generated by Django 3.0.7 on 2020-07-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200630_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
